// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"embed"
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

//go:embed app.slint
var slintFS embed.FS

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.CompileFS(slintFS, "app.slint", slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

var generatedSourceRel = "app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*Clock) error
	recording bool
}

// Clock is a typed wrapper around the "Clock" component.
type Clock struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewClock compiles (once) and instantiates the component.
func NewClock() (*Clock, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("Clock")
	if err != nil {
		return nil, err
	}
	c := &Clock{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

func (c *Clock) Inner() *slint.Instance { return c.inner }
func (c *Clock) Show() error            { return c.inner.Show() }
func (c *Clock) Hide() error            { return c.inner.Hide() }
func (c *Clock) Close()                 { c.inner.Close() }
func (c *Clock) RequestClose()          { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *Clock) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "Clock", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&Clock{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *Clock) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Clock) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *Clock) RegisterFontFromPath(path string) error { return c.inner.RegisterFontFromPath(path) }
func (c *Clock) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *Clock) Ticks() (int, error) {
	v, err := c.inner.Get("ticks")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *Clock) SetTicks(value int) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Clock) error { return t.SetTicks(value) })
	}
	return c.inner.Set("ticks", value)
}
