// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { VerticalBox } from \"std-widgets.slint\";\n\nexport component Clock inherits Window {\n    title: \"go-slint clock\";\n    preferred-width: 240px;\n    preferred-height: 120px;\n\n    in-out property <int> ticks: 0;\n\n    VerticalBox {\n        alignment: center;\n        Text {\n            text: \"Ticks: \" + root.ticks;\n            font-size: 28px;\n            horizontal-alignment: center;\n        }\n    }\n}\n"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

// Clock is a typed wrapper around the "Clock" component.
type Clock struct{ inner *slint.Instance }

// NewClock compiles (once) and instantiates the component.
func NewClock() (*Clock, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("Clock")
	if err != nil {
		return nil, err
	}
	return &Clock{inner: inner}, nil
}

func (c *Clock) Inner() *slint.Instance { return c.inner }
func (c *Clock) Show() error            { return c.inner.Show() }
func (c *Clock) Hide() error            { return c.inner.Hide() }
func (c *Clock) Run() error             { return c.inner.Run() }
func (c *Clock) Close()                 { c.inner.Close() }
func (c *Clock) RequestClose()          { c.inner.RequestClose() }

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *Clock) OnCloseRequested(handler func() bool) { c.inner.OnCloseRequested(handler) }

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *Clock) RegisterFontFromPath(path string) error { return c.inner.RegisterFontFromPath(path) }
func (c *Clock) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *Clock) Ticks() (int, error) {
	v, err := c.inner.Get("ticks")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *Clock) SetTicks(value int) error {
	return c.inner.Set("ticks", value)
}
