// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { VerticalBox } from \"std-widgets.slint\";\n\nexport component Clock inherits Window {\n    title: \"go-slint clock\";\n    preferred-width: 240px;\n    preferred-height: 120px;\n\n    in-out property <int> ticks: 0;\n\n    VerticalBox {\n        alignment: center;\n        Text {\n            text: \"Ticks: \" + root.ticks;\n            font-size: 28px;\n            horizontal-alignment: center;\n        }\n    }\n}\n"

var generatedSourceRel = "../app.slint"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

// sourcePath locates the .slint next to the generated file at runtime, so
// relative imports resolve from disk. Returns false if it isn't there (e.g. a
// shipped single-file binary), in which case the embedded source is used.
func sourcePath() (string, bool) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", false
	}
	p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
	if _, err := os.Stat(p); err != nil {
		return "", false
	}
	return p, true
}

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		if p, ok := sourcePath(); ok {
			compiled, compileErr = slint.CompileSource(p, generatedSource, slint.WithStyle("fluent"), slint.WithIncludePaths(filepath.Dir(p)))
		} else {
			compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
		}
	})
	return compiled, compileErr
}

// Clock is a typed wrapper around the "Clock" component.
type Clock struct{ inner *slint.Instance }

// NewClock compiles (once) and instantiates the component.
func NewClock() (*Clock, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("Clock")
	if err != nil {
		return nil, err
	}
	return &Clock{inner: inner}, nil
}

func (c *Clock) Inner() *slint.Instance { return c.inner }
func (c *Clock) Show() error            { return c.inner.Show() }
func (c *Clock) Hide() error            { return c.inner.Hide() }
func (c *Clock) Run() error             { return c.inner.Run() }
func (c *Clock) Close()                 { c.inner.Close() }

func (c *Clock) Ticks() (int, error) {
	v, err := c.inner.Get("ticks")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *Clock) SetTicks(value int) error {
	return c.inner.Set("ticks", value)
}
