// Code generated by goslint. DO NOT EDIT.
//
// This typed API is thread-affine: call New*, the property/callback/function
// methods, and Run on one OS-locked goroutine (the one that runs the event loop).
// Use slint.InvokeFromEventLoop to touch the UI from another goroutine.

package ui

import (
	"embed"
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

//go:embed app.slint
var slintFS embed.FS

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.CompileFS(slintFS, "app.slint", slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

var generatedSourceRel = "app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*AppWindow) error
	recording bool
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	c := &AppWindow{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

// Inner returns the underlying *slint.Instance for lower-level access.
func (c *AppWindow) Inner() *slint.Instance { return c.inner }

// Show makes the window visible without blocking.
func (c *AppWindow) Show() error { return c.inner.Show() }

// Hide hides the window.
func (c *AppWindow) Hide() error { return c.inner.Hide() }

// Close releases the component's native resources.
func (c *AppWindow) Close() { c.inner.Close() }

// RequestClose asks the window to close (fires the OnCloseRequested handler).
func (c *AppWindow) RequestClose() { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *AppWindow) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "AppWindow", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&AppWindow{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *AppWindow) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath registers a custom font file for use via `font-family`.
func (c *AppWindow) RegisterFontFromPath(path string) error {
	return c.inner.RegisterFontFromPath(path)
}

// RegisterFontFromMemory registers a custom font from memory for use via `font-family`.
func (c *AppWindow) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

// Frame returns the "frame" property.
func (c *AppWindow) Frame() (*slint.Image, error) {
	v, err := c.inner.Get("frame")
	if err != nil {
		var zero *slint.Image
		return zero, err
	}
	return slint.As[*slint.Image](v)
}

// SetFrame sets the "frame" property.
func (c *AppWindow) SetFrame(value *slint.Image) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.SetFrame(value) })
	}
	return c.inner.Set("frame", value)
}
