package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// cmdInit scaffolds a new go-slint project using the TYPED API: app.slint, a
// pre-generated ui/app.slint.go (so it builds right after `goslint setup`),
// app.go (shared wiring + a //go:generate directive to regenerate), and the
// desktop + Android entry points.
func cmdInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ExitOnError)
	module := fs.String("module", "", "Go module path (default: directory name)")
	_ = fs.Parse(args)

	dir := fs.Arg(0)
	if dir == "" {
		dir = "."
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	name := filepath.Base(abs)
	if name == "." || name == string(filepath.Separator) {
		name = "goslint-app"
	}
	if *module == "" {
		*module = name
	}

	if err := os.MkdirAll(filepath.Join(dir, "ui"), 0o755); err != nil {
		return err
	}
	if exists(filepath.Join(dir, "app.go")) {
		return fmt.Errorf("%s already contains app.go — refusing to overwrite", dir)
	}

	if !exists(filepath.Join(dir, "go.mod")) {
		if err := runIn(dir, "go", "mod", "init", *module); err != nil {
			return err
		}
	}
	if err := runIn(dir, "go", "mod", "edit", "-require="+modulePath+"@"+version()); err != nil {
		return err
	}

	files := map[string]string{
		"app.slint":       appSlintTemplate,
		"ui/app.slint.go": uiTemplate,
		"app.go":          fmt.Sprintf(appGoTemplate, *module),
		"main.go":         mainTemplate,
		"app_android.go":  androidTemplate,
	}
	for rel, content := range files {
		if err := os.WriteFile(filepath.Join(dir, rel), []byte(content), 0o644); err != nil {
			return err
		}
	}

	// best-effort: pull the dependency (needs the module to be reachable)
	if err := runIn(dir, "go", "mod", "tidy"); err != nil {
		fmt.Printf("\nnote: `go mod tidy` failed (is %s published/reachable yet?). Run it once it is.\n", modulePath)
	}

	fmt.Printf("\n✓ scaffolded %q (typed API) in %s\n\nNext:\n", name, dir)
	if dir != "." {
		fmt.Printf("  cd %s\n", dir)
	}
	fmt.Println("  goslint setup            # fetch the native lib for this platform")
	fmt.Println("  goslint dev .            # run with auto-reload on edits")
	fmt.Println("  goslint android build .  # build a signed APK")
	fmt.Println("\nJust edit app.slint — goslint dev/run/build regenerate ui/app.slint.go for you.")
	return nil
}

func runIn(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	return cmd.Run()
}

const appSlintTemplate = `import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> count: 0;
    callback increment();

    title: "go-slint app";
    preferred-width: 320px;
    preferred-height: 200px;

    VerticalBox {
        alignment: center;
        spacing: 12px;
        Text {
            text: "Count: " + root.count;
            font-size: 28px;
            horizontal-alignment: center;
        }
        Button {
            text: "Increment";
            clicked => { root.increment(); }
        }
    }
}
`

// appGoTemplate holds the shared wiring (used by both desktop and Android). %s is
// the module path (for the ui import).
const appGoTemplate = `package main

//go:generate goslint generate -o ui/app.slint.go -package ui app.slint

import (
	"%s/ui"
)

// wire binds callbacks and initial state on the typed window.
func wire(win *ui.AppWindow) error {
	return win.OnIncrement(func() {
		n, _ := win.Count()
		_ = win.SetCount(n + 1)
	})
}

func run() error {
	win, err := ui.NewAppWindow()
	if err != nil {
		return err
	}
	defer win.Close()
	if err := wire(win); err != nil {
		return err
	}
	return win.Run()
}
`

const mainTemplate = `//go:build !android

package main

import "runtime"

func init() { runtime.LockOSThread() } // Slint is thread-affine

func main() {
	if err := run(); err != nil {
		panic(err)
	}
}
`

const androidTemplate = `//go:build android

package main

import "C"

import "runtime"

//export goslint_android_main
func goslint_android_main(_ *C.char) {
	runtime.LockOSThread()
	_ = run()
}

func main() {} // required for c-shared; unused (entry is goslint_android_main)
`

// uiTemplate is the typed wrapper for the scaffold's app.slint, pre-generated by
// goslint-gen so the project builds before the user runs `go generate`.
const uiTemplate = "// Code generated by goslint. DO NOT EDIT.\n\n" + `package ui

import (
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { Button, VerticalBox } from \"std-widgets.slint\";\n\nexport component AppWindow inherits Window {\n    in-out property <int> count: 0;\n    callback increment();\n\n    title: \"go-slint app\";\n    preferred-width: 320px;\n    preferred-height: 200px;\n\n    VerticalBox {\n        alignment: center;\n        spacing: 12px;\n        Text {\n            text: \"Count: \" + root.count;\n            font-size: 28px;\n            horizontal-alignment: center;\n        }\n        Button {\n            text: \"Increment\";\n            clicked => { root.increment(); }\n        }\n    }\n}\n"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct{ inner *slint.Instance }

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	return &AppWindow{inner: inner}, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Run() error             { return c.inner.Run() }
func (c *AppWindow) Close()                 { c.inner.Close() }

func (c *AppWindow) Count() (int, error) {
	v, err := c.inner.Get("count")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *AppWindow) SetCount(value int) error {
	return c.inner.Set("count", value)
}

func (c *AppWindow) OnIncrement(handler func()) error {
	return c.inner.OnCallback("increment", func(args []any) any {
		handler()
		return nil
	})
}
`
