// Command counter is an interactive go-slint example using the TYPED API
// (generated by `goslint generate` — see the directive). Button clicks are
// handled in Go via typed callbacks that update the typed `value` property.
//
//	make lib
//	go run ./cmd/examples/counter   # or: goslint dev ./cmd/examples/counter (live reload)
package main

//go:generate goslint generate -o ui/app.slint.go -package ui ui/app.slint

import (
	"log"
	"runtime"

	"github.com/rileylov/go-slint/cmd/examples/counter/ui"
)

// Slint is thread-affine: pin the main goroutine.
func init() { runtime.LockOSThread() }

func main() {
	win, err := ui.NewCounter()
	if err != nil {
		log.Fatal(err)
	}
	defer win.Close()

	win.OnIncrement(func() {
		v, _ := win.Value()
		_ = win.SetValue(v + 1)
	})
	win.OnReset(func() {
		_ = win.SetValue(0)
	})

	// Run normally; under `goslint dev` the same code live-reloads app.slint.
	if err := win.Run(); err != nil {
		log.Fatal(err)
	}
}
