// Command typed is the hello example using the TYPED API generated by
// `goslint generate` (see the //go:generate directive). Compare with the dynamic
// examples (counter/clock/…): here property and callback names are real Go
// methods, checked by the compiler.
//
//	make lib
//	go generate ./examples/typed   # regenerates ui/app.slint.go from app.slint
//	go run ./examples/typed        # or: goslint dev ./examples/typed (live reload)
package main

//go:generate goslint generate -o ui/app.slint.go -package ui ui/app.slint

import (
	"fmt"
	"runtime"
	"strings"

	slint "github.com/rileylov/go-slint"
	"github.com/rileylov/go-slint/examples/typed/ui"
)

func init() { runtime.LockOSThread() } // Slint is thread-affine

func main() {

	win, err := ui.NewAppWindow()
	if err != nil {
		panic(err)
	}
	defer win.Close()

	app := win.App()

	if err := app.OnGreeting(func(name string) string {
		return "Hello, " + strings.ToUpper(name) + "!"
	}); err != nil {
		panic(err)
	}

	logs := slint.NewSliceModel()
	if err := win.SetLogModel(logs); err != nil {
		panic(err)
	}

	if err := app.OnClicked(func() {
		n, _ := app.Calls()
		if err := app.SetCalls(n + 1); err != nil {
			fmt.Println("set global App.calls failed:", err)
			return
		}
		win.SetClicks(n + 1)

		// Slint rerenders only the changed rows, not the whole list.
		logs.Append(fmt.Sprintf("click #%d", n+1))
		for logs.Len() > 5 {
			logs.RemoveAt(0)
		}
	}); err != nil {
		panic(err)
	}

	if err := win.SetName("Gophers"); err != nil {
		panic(err)
	}

	if err := win.Run(); err != nil {
		panic(err)
	}
}
