// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { Button, VerticalBox } from \"std-widgets.slint\";\n\nexport component Counter inherits Window {\n    title: \"go-slint counter\";\n    preferred-width: 280px;\n    preferred-height: 180px;\n\n    in-out property <int> value: 0;\n    callback increment();\n    callback reset();\n\n    VerticalBox {\n        alignment: center;\n        Text {\n            text: \"Count: \" + root.value;\n            font-size: 28px;\n            horizontal-alignment: center;\n        }\n        Button {\n            text: \"Increment\";\n            clicked => { root.increment(); }\n        }\n        Button {\n            text: \"Reset\";\n            clicked => { root.reset(); }\n        }\n    }\n}\n"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

var generatedSourceRel = "../app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*Counter) error
	recording bool
}

// Counter is a typed wrapper around the "Counter" component.
type Counter struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewCounter compiles (once) and instantiates the component.
func NewCounter() (*Counter, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("Counter")
	if err != nil {
		return nil, err
	}
	c := &Counter{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

func (c *Counter) Inner() *slint.Instance { return c.inner }
func (c *Counter) Show() error            { return c.inner.Show() }
func (c *Counter) Hide() error            { return c.inner.Hide() }
func (c *Counter) Close()                 { c.inner.Close() }
func (c *Counter) RequestClose()          { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *Counter) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "Counter", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&Counter{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *Counter) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *Counter) RegisterFontFromPath(path string) error { return c.inner.RegisterFontFromPath(path) }
func (c *Counter) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *Counter) Value() (int, error) {
	v, err := c.inner.Get("value")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *Counter) SetValue(value int) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.SetValue(value) })
	}
	return c.inner.Set("value", value)
}

func (c *Counter) OnIncrement(handler func()) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.OnIncrement(handler) })
	}
	return c.inner.OnCallback("increment", func(args []any) any {
		handler()
		return nil
	})
}

func (c *Counter) OnReset(handler func()) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.OnReset(handler) })
	}
	return c.inner.OnCallback("reset", func(args []any) any {
		handler()
		return nil
	})
}
