// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { Button, VerticalBox } from \"std-widgets.slint\";\n\nexport global Logic {\n    pure callback greeting(string) -> string;\n}\n\nexport component AppWindow inherits Window {\n    in-out property <string> name: \"World\";\n    in-out property <int> clicks: 0;\n    in-out property <[string]> log;\n    callback clicked();\n\n    title: \"Typed Hello\";\n    preferred-width: 340px;\n    preferred-height: 260px;\n\n    VerticalBox {\n        alignment: center;\n        spacing: 10px;\n        Text { text: Logic.greeting(root.name); horizontal-alignment: center; font-size: 22px; }\n        Text { text: \"clicks: \" + root.clicks; horizontal-alignment: center; color: #888; }\n        Button { text: \"Click me\"; clicked => { root.clicked(); } }\n        for entry in root.log : Text { text: entry; horizontal-alignment: center; color: #44aa88; }\n    }\n}\n"

var generatedSourceRel = "../app.slint"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

// sourcePath locates the .slint next to the generated file at runtime, so
// relative imports resolve from disk. Returns false if it isn't there (e.g. a
// shipped single-file binary), in which case the embedded source is used.
func sourcePath() (string, bool) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", false
	}
	p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
	if _, err := os.Stat(p); err != nil {
		return "", false
	}
	return p, true
}

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		if p, ok := sourcePath(); ok {
			compiled, compileErr = slint.CompileSource(p, generatedSource, slint.WithStyle("fluent"), slint.WithIncludePaths(filepath.Dir(p)))
		} else {
			compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
		}
	})
	return compiled, compileErr
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct{ inner *slint.Instance }

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	return &AppWindow{inner: inner}, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Run() error             { return c.inner.Run() }
func (c *AppWindow) Close()                 { c.inner.Close() }

func (c *AppWindow) Clicks() (int, error) {
	v, err := c.inner.Get("clicks")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *AppWindow) SetClicks(value int) error {
	return c.inner.Set("clicks", value)
}

func (c *AppWindow) Log() ([]string, error) {
	v, err := c.inner.Get("log")
	if err != nil {
		var zero []string
		return zero, err
	}
	return func() []string {
		raw, _ := v.([]any)
		out := make([]string, 0, len(raw))
		for _, e := range raw {
			out = append(out, e.(string))
		}
		return out
	}(), nil
}

func (c *AppWindow) SetLog(value []string) error {
	return c.inner.Set("log", func() []any {
		src := value
		out := make([]any, len(src))
		for i, e := range src {
			out[i] = e
		}
		return out
	}())
}

func (c *AppWindow) Name() (string, error) {
	v, err := c.inner.Get("name")
	if err != nil {
		var zero string
		return zero, err
	}
	return v.(string), nil
}

func (c *AppWindow) SetName(value string) error {
	return c.inner.Set("name", value)
}

func (c *AppWindow) OnClicked(handler func()) error {
	return c.inner.OnCallback("clicked", func(args []any) any {
		handler()
		return nil
	})
}

// Logic() accesses the "Logic" global.
func (c *AppWindow) Logic() *AppWindowLogic { return &AppWindowLogic{inner: c.inner} }

type AppWindowLogic struct{ inner *slint.Instance }

func (g *AppWindowLogic) OnGreeting(handler func(a0 string) string) error {
	return g.inner.OnGlobalCallback("Logic", "greeting", func(args []any) any {
		return handler(args[0].(string))
	})
}
