// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"embed"
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

//go:embed app.slint
var slintFS embed.FS

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.CompileFS(slintFS, "app.slint", slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

var generatedSourceRel = "app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*AppWindow) error
	recording bool
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	c := &AppWindow{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Close()                 { c.inner.Close() }
func (c *AppWindow) RequestClose()          { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *AppWindow) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "AppWindow", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&AppWindow{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *AppWindow) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *AppWindow) RegisterFontFromPath(path string) error {
	return c.inner.RegisterFontFromPath(path)
}
func (c *AppWindow) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *AppWindow) Clicks() (int, error) {
	v, err := c.inner.Get("clicks")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *AppWindow) SetClicks(value int) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.SetClicks(value) })
	}
	return c.inner.Set("clicks", value)
}

func (c *AppWindow) Log() ([]string, error) {
	v, err := c.inner.Get("log")
	if err != nil {
		var zero []string
		return zero, err
	}
	return func() []string {
		raw, _ := v.([]any)
		out := make([]string, 0, len(raw))
		for _, e := range raw {
			out = append(out, e.(string))
		}
		return out
	}(), nil
}

func (c *AppWindow) SetLog(value []string) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.SetLog(value) })
	}
	return c.inner.Set("log", func() []any {
		src := value
		out := make([]any, len(src))
		for i, e := range src {
			out[i] = e
		}
		return out
	}())
}

func (c *AppWindow) Name() (string, error) {
	v, err := c.inner.Get("name")
	if err != nil {
		var zero string
		return zero, err
	}
	return v.(string), nil
}

func (c *AppWindow) SetName(value string) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.SetName(value) })
	}
	return c.inner.Set("name", value)
}

// App() accesses the "App" global.
func (c *AppWindow) App() *AppWindowApp { return &AppWindowApp{owner: c} }

type AppWindowApp struct {
	owner *AppWindow
}

func (g *AppWindowApp) Calls() (int, error) {
	v, err := g.owner.inner.GetGlobal("App", "calls")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (g *AppWindowApp) SetCalls(value int) error {
	if g.owner.rec != nil && g.owner.rec.recording {
		g.owner.rec.replays = append(g.owner.rec.replays, func(t *AppWindow) error { return t.App().SetCalls(value) })
	}
	return g.owner.inner.SetGlobal("App", "calls", value)
}

func (g *AppWindowApp) OnClicked(handler func()) error {
	if g.owner.rec != nil && g.owner.rec.recording {
		g.owner.rec.replays = append(g.owner.rec.replays, func(t *AppWindow) error { return t.App().OnClicked(handler) })
	}
	return g.owner.inner.OnGlobalCallback("App", "Clicked", func(args []any) any {
		handler()
		return nil
	})
}

func (g *AppWindowApp) OnGreeting(handler func(a0 string) string) error {
	if g.owner.rec != nil && g.owner.rec.recording {
		g.owner.rec.replays = append(g.owner.rec.replays, func(t *AppWindow) error { return t.App().OnGreeting(handler) })
	}
	return g.owner.inner.OnGlobalCallback("App", "Greeting", func(args []any) any {
		return handler(args[0].(string))
	})
}
