// Command typed is the hello example using the TYPED API generated by
// `goslint generate` (see the //go:generate directive). Compare with the dynamic
// examples (counter/clock/…): here property and callback names are real Go
// methods, checked by the compiler.
//
//	make lib
//	go generate ./cmd/examples/typed   # regenerates ui/app.slint.go from app.slint
//	go run ./cmd/examples/typed
package main

//go:generate goslint generate -o ui/app.slint.go -package ui app.slint

import (
	"runtime"
	"strings"

	"github.com/rileylov/go-slint/cmd/examples/typed/ui"
)

func init() { runtime.LockOSThread() } // Slint is thread-affine

func main() {
	win, err := ui.NewAppWindow()
	if err != nil {
		panic(err)
	}
	defer win.Close()

	// typed global callback: signature matches the .slint declaration
	if err := win.Logic().OnGreeting(func(name string) string {
		return "Hello, " + strings.ToUpper(name) + "!"
	}); err != nil {
		panic(err)
	}

	// typed property setter
	if err := win.SetName("Gophers"); err != nil {
		panic(err)
	}

	// typed callback + typed property get/set
	if err := win.OnClicked(func() {
		n, _ := win.Clicks()
		_ = win.SetClicks(n + 1)
	}); err != nil {
		panic(err)
	}

	if err := win.Run(); err != nil {
		panic(err)
	}
}
