// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"os"
	pathpkg "path"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { VerticalBox, Button } from \"std-widgets.slint\";\nimport { Card } from \"components/card.slint\";\n\nexport component AppWindow inherits Window {\n    in-out property <int> count: 0;\n    callback bump();\n\n    title: \"Multi-file\";\n    preferred-width: 320px;\n    preferred-height: 220px;\n\n    VerticalBox {\n        Card { title: \"Counter\"; value: root.count; }\n        Button { text: \"Bump\"; clicked => { root.bump(); } }\n    }\n}\n"

var generatedSourceRel = "../app.slint"

// generatedEntryName is the entry .slint's base name; it's the path the
// embedded file-loader treats imports as relative to.
var generatedEntryName = "app.slint"

// generatedFiles holds every imported .slint, keyed relative to the entry's
// directory, so the component compiles from memory with no files on disk.
var generatedFiles = map[string]string{
	"components/card.slint": "import { VerticalBox } from \"std-widgets.slint\";\n\n// Card is a reusable component imported by app.slint, demonstrating that the typed\n// generator embeds every imported .slint so the binary is self-contained.\nexport component Card inherits Rectangle {\n    in property <string> title;\n    in property <int> value;\n\n    background: #2a2a2a;\n    border-radius: 8px;\n    height: 96px;\n\n    VerticalBox {\n        Text { text: root.title; font-size: 14px; color: #999; }\n        Text { text: root.value; font-size: 34px; horizontal-alignment: center; }\n    }\n}\n",
}

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

// sourcePath locates the .slint next to the generated file at runtime, so
// relative imports resolve from disk. Returns false if it isn't there (e.g. a
// shipped binary), in which case the embedded source is used.
func sourcePath() (string, bool) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", false
	}
	p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
	if _, err := os.Stat(p); err != nil {
		return "", false
	}
	return p, true
}

// embeddedLoader resolves imports from generatedFiles (the requested path is
// relative to the entry's directory).
func embeddedLoader(path string) (string, bool) {
	s, ok := generatedFiles[pathpkg.Clean(filepath.ToSlash(path))]
	return s, ok
}

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		if p, ok := sourcePath(); ok {
			compiled, compileErr = slint.CompileSource(p, generatedSource, slint.WithStyle("fluent"), slint.WithIncludePaths(filepath.Dir(p)))
		} else {
			compiled, compileErr = slint.CompileSource(generatedEntryName, generatedSource, slint.WithStyle("fluent"), slint.WithFileLoader(embeddedLoader))
		}
	})
	return compiled, compileErr
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct{ inner *slint.Instance }

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	return &AppWindow{inner: inner}, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Run() error             { return c.inner.Run() }
func (c *AppWindow) Close()                 { c.inner.Close() }

func (c *AppWindow) Count() (int, error) {
	v, err := c.inner.Get("count")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *AppWindow) SetCount(value int) error {
	return c.inner.Set("count", value)
}

func (c *AppWindow) OnBump(handler func()) error {
	return c.inner.OnCallback("bump", func(args []any) any {
		handler()
		return nil
	})
}
