// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"os"
	pathpkg "path"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { VerticalBox, Button } from \"std-widgets.slint\";\nimport { Card } from \"components/card.slint\";\n\nexport component AppWindow inherits Window {\n    in-out property <int> count: 0;\n    callback bump();\n\n    title: \"Multi-file\";\n    preferred-width: 320px;\n    preferred-height: 220px;\n\n    VerticalBox {\n        Card { title: \"Counter\"; value: root.count; }\n        Button { text: \"Bump\"; clicked => { root.bump(); } }\n    }\n}\n"

// generatedEntryName is the entry .slint's base name; the embedded file-loader
// treats imports as relative to it.
var generatedEntryName = "app.slint"

// generatedFiles holds every imported .slint, keyed relative to the entry's
// directory, so the component compiles from memory with no files on disk.
var generatedFiles = map[string]string{
	"components/card.slint": "import { VerticalBox } from \"std-widgets.slint\";\n\n// Card is a reusable component imported by app.slint, demonstrating that the typed\n// generator embeds every imported .slint so the binary is self-contained.\nexport component Card inherits Rectangle {\n    in property <string> title;\n    in property <int> value;\n\n    background: #2a2a2a;\n    border-radius: 8px;\n    height: 96px;\n\n    VerticalBox {\n        Text { text: root.title; font-size: 14px; color: #999; }\n        Text { text: root.value; font-size: 34px; horizontal-alignment: center; }\n    }\n}\n",
}

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

// embeddedLoader resolves imports from generatedFiles (the requested path is
// relative to the entry's directory).
func embeddedLoader(path string) (string, bool) {
	s, ok := generatedFiles[pathpkg.Clean(filepath.ToSlash(path))]
	return s, ok
}

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.CompileSource(generatedEntryName, generatedSource, slint.WithStyle("fluent"), slint.WithFileLoader(embeddedLoader))
	})
	return compiled, compileErr
}

var generatedSourceRel = "../app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*AppWindow) error
	recording bool
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	c := &AppWindow{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Close()                 { c.inner.Close() }
func (c *AppWindow) RequestClose()          { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *AppWindow) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "AppWindow", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&AppWindow{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *AppWindow) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *AppWindow) RegisterFontFromPath(path string) error {
	return c.inner.RegisterFontFromPath(path)
}
func (c *AppWindow) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *AppWindow) Count() (int, error) {
	v, err := c.inner.Get("count")
	if err != nil {
		var zero int
		return zero, err
	}
	return int(v.(float64)), nil
}

func (c *AppWindow) SetCount(value int) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.SetCount(value) })
	}
	return c.inner.Set("count", value)
}

func (c *AppWindow) OnBump(handler func()) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *AppWindow) error { return t.OnBump(handler) })
	}
	return c.inner.OnCallback("bump", func(args []any) any {
		handler()
		return nil
	})
}
