package main

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
)

// generate produces the typed Go source for a component interface. relPath is the
// entry .slint's path relative to the output .go — a bare filename, since the binding
// is co-located with the markup. files holds every transitively-imported local .slint
// keyed relative to the entry's directory. The entry and its imports are emitted as a
// //go:embed list, so the .slint stays the single source of truth and the binary is
// self-contained.
func generate(iface *Interface, pkg, style, relPath string, files map[string]string) ([]byte, error) {
	// Fail loudly on identifier collisions/invalid names before emitting anything:
	// format.Source only parses the output, so a duplicate method would slip through
	// and break the user's build with a confusing error.
	if err := validateNames(iface); err != nil {
		return nil, err
	}

	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	// Co-location invariant: //go:embed reaches down, never up — so the generated .go
	// must sit in the entry .slint's directory, with every import at or below it.
	// relPath is the entry relative to the output .go's dir; co-location makes it a
	// bare filename.
	if strings.Contains(relPath, "/") {
		return nil, fmt.Errorf("entry .slint must be in the same directory as the generated .go (got %q); co-locate the markup with the binding, e.g. ui/app.slint + ui/app.slint.go", relPath)
	}
	embedPaths := []string{relPath}
	for _, k := range sortedKeys(files) {
		if k == ".." || strings.HasPrefix(k, "../") {
			return nil, fmt.Errorf("imported .slint %q is outside the binding's directory; //go:embed can't reach up — keep all imported markup at or below the generated package", k)
		}
		embedPaths = append(embedPaths, k)
	}

	p("// Code generated by goslint. DO NOT EDIT.\n//\n")
	p("// This typed API is thread-affine: call New*, the property/callback/function\n")
	p("// methods, and Run on one OS-locked goroutine (the one that runs the event loop).\n")
	p("// Use slint.InvokeFromEventLoop to touch the UI from another goroutine.\n\n")
	p("package %s\n\n", pkg)
	p("import (\n\t\"embed\"\n\t\"os\"\n\t\"path/filepath\"\n\t\"runtime\"\n\t\"sync\"\n\n\tslint \"github.com/rileylov/go-slint\"\n)\n\n")

	// The .slint markup is embedded by reference (not baked as Go string literals), so
	// it stays the single source of truth in the repo and the binary is self-contained.
	// CompileFS resolves the entry's imports through this same embedded FS.
	p("//go:embed %s\n", strings.Join(embedPaths, " "))
	p("var slintFS embed.FS\n\n")
	p("var (\n\tcompileOnce sync.Once\n\tcompiled    *slint.Compilation\n\tcompileErr  error\n)\n\n")
	p("func compile() (*slint.Compilation, error) {\n")
	p("\tcompileOnce.Do(func() {\n")
	p("\t\tcompiled, compileErr = slint.CompileFS(slintFS, %q, slint.WithStyle(%q))\n", relPath, style)
	p("\t})\n")
	p("\treturn compiled, compileErr\n}\n\n")

	comp := exported(iface.Component)

	// dev-only: the entry .slint sits next to this generated file, so goslint dev can
	// locate it on disk to hot-reload (imports resolve from disk during dev).
	p("var generatedSourceRel = %q\n\n", relPath)
	p("func sourcePath() (string, bool) {\n")
	p("\t// Primary: next to this generated file (source tree present — go run / goslint dev).\n")
	p("\tif _, file, _, ok := runtime.Caller(0); ok {\n")
	p("\t\tp := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))\n")
	p("\t\tif _, err := os.Stat(p); err == nil {\n\t\t\treturn p, true\n\t\t}\n")
	p("\t}\n")
	p("\t// Fallback: the entry .slint in the working directory (goslint dev runs from\n")
	p("\t// the project dir) — robust even if generatedSourceRel doesn't resolve.\n")
	p("\tif wd, err := os.Getwd(); err == nil {\n")
	p("\t\tp := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))\n")
	p("\t\tif _, err := os.Stat(p); err == nil {\n\t\t\treturn p, true\n\t\t}\n")
	p("\t}\n")
	p("\treturn \"\", false\n}\n\n")

	// devRecorder records the setup calls (Set*/On*) made between New and Run so they
	// can be replayed on each live reload onto the freshly-compiled instance.
	p("type devRecorder struct {\n\treplays   []func(*%s) error\n\trecording bool\n}\n\n", comp)

	// component type + constructor + lifecycle
	p("// %s is a typed wrapper around the %q component.\n", comp, iface.Component)
	p("type %s struct {\n\tinner *slint.Instance\n\trec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload\n}\n\n", comp)
	p("// New%s compiles (once) and instantiates the component.\n", comp)
	p("func New%s() (*%s, error) {\n", comp, comp)
	p("\tapp, err := compile()\n\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	p("\tinner, err := app.Create(%q)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n", iface.Component)
	p("\tc := &%s{inner: inner}\n", comp)
	p("\tif os.Getenv(\"GOSLINT_DEV\") != \"\" {\n\t\tc.rec = &devRecorder{recording: true}\n\t}\n")
	p("\treturn c, nil\n}\n\n")
	p("// Inner returns the underlying *slint.Instance for lower-level access.\n")
	p("func (c *%s) Inner() *slint.Instance { return c.inner }\n", comp)
	p("// Show makes the window visible without blocking.\n")
	p("func (c *%s) Show() error { return c.inner.Show() }\n", comp)
	p("// Hide hides the window.\n")
	p("func (c *%s) Hide() error { return c.inner.Hide() }\n", comp)
	p("// Close releases the component's native resources.\n")
	p("func (c *%s) Close()      { c.inner.Close() }\n", comp)
	p("// RequestClose asks the window to close (fires the OnCloseRequested handler).\n")
	p("func (c *%s) RequestClose() { c.inner.RequestClose() }\n", comp)
	// Run: in dev (GOSLINT_DEV + .slint on disk) replay the recorded setup on each
	// live reload via slint.LiveReload; otherwise just run.
	p("// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads\n")
	p("// the .slint in-process, replaying your setup on each reload.\n")
	p("func (c *%s) Run() error {\n", comp)
	p("\tif c.rec != nil {\n")
	p("\t\tc.rec.recording = false\n")
	p("\t\tif p, ok := sourcePath(); ok {\n")
	p("\t\t\tc.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own\n")
	p("\t\t\treturn slint.LiveReload(p, %q, func(inst *slint.Instance) error {\n", iface.Component)
	p("\t\t\t\tc.inner = inst\n")
	p("\t\t\t\tfor _, replay := range c.rec.replays {\n")
	p("\t\t\t\t\tif err := replay(&%s{inner: inst}); err != nil {\n\t\t\t\t\t\treturn err\n\t\t\t\t\t}\n", comp)
	p("\t\t\t\t}\n\t\t\t\treturn nil\n")
	p("\t\t\t}, slint.WithStyle(%q))\n", style)
	p("\t\t}\n\t}\n")
	p("\treturn c.inner.Run()\n}\n")
	p("// OnCloseRequested runs when the window's close is requested; return true to allow it to close.\n")
	p("func (c *%s) OnCloseRequested(handler func() bool) {\n", comp)
	p("\tif c.rec != nil && c.rec.recording {\n\t\tc.rec.replays = append(c.rec.replays, func(t *%s) error { t.OnCloseRequested(handler); return nil })\n\t}\n", comp)
	p("\tc.inner.OnCloseRequested(handler)\n}\n")
	p("// RegisterFontFromPath registers a custom font file for use via `font-family`.\n")
	p("func (c *%s) RegisterFontFromPath(path string) error { return c.inner.RegisterFontFromPath(path) }\n", comp)
	p("// RegisterFontFromMemory registers a custom font from memory for use via `font-family`.\n")
	p("func (c *%s) RegisterFontFromMemory(data []byte) error { return c.inner.RegisterFontFromMemory(data) }\n\n", comp)

	recv := "c *" + comp
	emitProperties(&b, recv, comp, iface.Properties, propAccessors{comp: comp, base: "c"})
	emitCallables(&b, recv, comp, iface.Callbacks, false, cbAccessors{comp: comp, base: "c"})
	emitCallables(&b, recv, comp, iface.Functions, true, cbAccessors{comp: comp, base: "c"})

	// globals. The accessor returns a handle holding a back-reference to the
	// component (not a snapshot of its *Instance), so a handle captured before Run()
	// stays valid across a dev live reload — which swaps the underlying instance.
	for _, g := range iface.Globals {
		gType := comp + exported(g.Name)
		acc := exported(g.Name)
		p("// %s() accesses the %q global.\n", acc, g.Name)
		p("func (c *%s) %s() *%s { return &%s{owner: c} }\n\n", comp, acc, gType, gType)
		p("// %s accesses the %q global's properties, callbacks, and functions.\n", gType, g.Name)
		p("type %s struct {\n\towner *%s\n}\n\n", gType, comp)
		grecv := "g *" + gType
		emitProperties(&b, grecv, gType, g.Properties, propAccessors{global: g.Name, comp: comp, accessor: acc, base: "g.owner"})
		emitCallables(&b, grecv, gType, g.Callbacks, false, cbAccessors{global: g.Name, comp: comp, accessor: acc, base: "g.owner"})
		emitCallables(&b, grecv, gType, g.Functions, true, cbAccessors{global: g.Name, comp: comp, accessor: acc, base: "g.owner"})
	}

	// structs & enums
	for _, name := range sortedKeys(iface.Structs) {
		emitStruct(&b, name, iface.Structs[name])
	}
	for _, name := range sortedKeys(iface.Enums) {
		emitEnum(&b, name, iface.Enums[name])
	}

	return format_(b.String())
}

// propAccessors / cbAccessors carry the global name (empty = component-level) plus
// the component type and Go global-accessor name (for dev record/replay), and
// `base` — the expression yielding the live instance/recorder: "c" for component
// members, "g.owner" for global members (which reach through the back-reference).
type propAccessors struct{ global, comp, accessor, base string }
type cbAccessors struct{ global, comp, accessor, base string }

// recordReplay emits the dev record branch for a setter/callback binding: when
// recording, append a closure that re-invokes `call` on a fresh component `t`.
func recordReplay(rcv, comp, call string) string {
	return fmt.Sprintf("\tif %s.rec != nil && %s.rec.recording {\n\t\t%s.rec.replays = append(%s.rec.replays, func(t *%s) error { return %s })\n\t}\n",
		rcv, rcv, rcv, rcv, comp, call)
}

func emitProperties(b *strings.Builder, recv, _ string, props []Prop, a propAccessors) {
	p := func(format string, x ...any) { fmt.Fprintf(b, format, x...) }
	for _, pr := range props {
		m := exported(pr.Name)
		gt := goType(pr.Ty)
		// getter
		p("// %s returns the %q property.\n", m, pr.Name)
		p("func (%s) %s() (%s, error) {\n", recv, m, gt)
		if a.global == "" {
			p("\tv, err := %s.inner.Get(%q)\n", a.base, pr.Name)
		} else {
			p("\tv, err := %s.inner.GetGlobal(%q, %q)\n", a.base, a.global, pr.Name)
		}
		p("\tif err != nil {\n\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", gt)
		p("\treturn %s, nil\n}\n\n", fromAny("v", pr.Ty))
		// setter — skipped for output-only properties (setting an `out` property fails
		// at runtime; an empty direction, e.g. from an older lib, keeps the setter).
		// Records for live-reload replay.
		if pr.Direction == "out" {
			continue
		}
		p("// Set%s sets the %q property.\n", m, pr.Name)
		p("func (%s) Set%s(value %s) error {\n", recv, m, gt)
		if a.global == "" {
			p("%s", recordReplay(a.base, a.comp, "t.Set"+m+"(value)"))
			p("\treturn %s.inner.Set(%q, %s)\n}\n\n", a.base, pr.Name, toAny("value", pr.Ty))
		} else {
			p("%s", recordReplay(a.base, a.comp, "t."+a.accessor+"().Set"+m+"(value)"))
			p("\treturn %s.inner.SetGlobal(%q, %q, %s)\n}\n\n", a.base, a.global, pr.Name, toAny("value", pr.Ty))
		}
	}
}

func emitCallables(b *strings.Builder, recv, _ string, cs []Callable, isFn bool, a cbAccessors) {
	p := func(format string, x ...any) { fmt.Fprintf(b, format, x...) }
	for _, c := range cs {
		params, argExprs := signature(c)
		if isFn {
			// function -> Invoke
			invokeArgs := strings.Join(prefixArgs(c), ", ")
			if c.Ret.Kind == "void" {
				p("// %s calls the %q function.\n", exported(c.Name), c.Name)
				p("func (%s) %s(%s) error {\n", recv, exported(c.Name), params)
				if a.global == "" {
					p("\t_, err := %s.inner.Invoke(%q%s)\n\treturn err\n}\n\n", a.base, c.Name, commaList(invokeArgs))
				} else {
					p("\t_, err := %s.inner.InvokeGlobal(%q, %q%s)\n\treturn err\n}\n\n", a.base, a.global, c.Name, commaList(invokeArgs))
				}
				continue
			}
			rt := goType(c.Ret)
			p("// %s calls the %q function.\n", exported(c.Name), c.Name)
			p("func (%s) %s(%s) (%s, error) {\n", recv, exported(c.Name), params, rt)
			if a.global == "" {
				p("\tr, err := %s.inner.Invoke(%q%s)\n", a.base, c.Name, commaList(invokeArgs))
			} else {
				p("\tr, err := %s.inner.InvokeGlobal(%q, %q%s)\n", a.base, a.global, c.Name, commaList(invokeArgs))
			}
			p("\tif err != nil {\n\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", rt)
			p("\treturn %s, nil\n}\n\n", fromAny("r", c.Ret))
			continue
		}
		// callback -> On<Name>(handler)
		sig := "func(" + params + ")"
		if c.Ret.Kind != "void" {
			sig += " " + goType(c.Ret)
		}
		p("// On%s registers a handler for the %q callback.\n", exported(c.Name), c.Name)
		p("func (%s) On%s(handler %s) error {\n", recv, exported(c.Name), sig)
		body := callbackBody(c, argExprs)
		if a.global == "" {
			p("%s", recordReplay(a.base, a.comp, "t.On"+exported(c.Name)+"(handler)"))
			p("\treturn %s.inner.OnCallback(%q, func(args []any) any {\n%s\t})\n}\n\n", a.base, c.Name, body)
		} else {
			p("%s", recordReplay(a.base, a.comp, "t."+a.accessor+"().On"+exported(c.Name)+"(handler)"))
			p("\treturn %s.inner.OnGlobalCallback(%q, %q, func(args []any) any {\n%s\t})\n}\n\n", a.base, a.global, c.Name, body)
		}
	}
}

// callbackBody converts args[] -> typed call, returns handler result as any.
func callbackBody(c Callable, _ []string) string {
	var call strings.Builder
	call.WriteString("handler(")
	for i, at := range c.Args {
		if i > 0 {
			call.WriteString(", ")
		}
		call.WriteString(fromAny(fmt.Sprintf("args[%d]", i), at))
	}
	call.WriteString(")")
	if c.Ret.Kind == "void" {
		return "\t\t" + call.String() + "\n\t\treturn nil\n"
	}
	return "\t\treturn " + toAny(call.String(), c.Ret) + "\n"
}

// signature builds the Go parameter list and the per-arg names.
func signature(c Callable) (params string, names []string) {
	var ps []string
	for i, at := range c.Args {
		n := fmt.Sprintf("a%d", i)
		names = append(names, n)
		ps = append(ps, n+" "+goType(at))
	}
	return strings.Join(ps, ", "), names
}

// prefixArgs converts typed params to any for Invoke.
func prefixArgs(c Callable) []string {
	var out []string
	for i, at := range c.Args {
		out = append(out, toAny(fmt.Sprintf("a%d", i), at))
	}
	return out
}

func commaList(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}

func emitStruct(b *strings.Builder, name string, s StructInfo) {
	p := func(format string, x ...any) { fmt.Fprintf(b, format, x...) }
	t := exported(name)
	p("// %s mirrors the Slint struct %q.\n", t, name)
	p("type %s struct {\n", t)
	for _, f := range s.Fields {
		p("\t%s %s\n", exported(f.Name), goType(f.Ty))
	}
	p("}\n\n")
	// FromMap
	p("func %sFromMap(m map[string]any) %s {\n\tvar s %s\n", unexported(t), t, t)
	for _, f := range s.Fields {
		p("\tif v, ok := m[%q]; ok {\n\t\ts.%s = %s\n\t}\n", f.Name, exported(f.Name), fromAny("v", f.Ty))
	}
	p("\treturn s\n}\n\n")
	// toMap
	p("func (s %s) toMap() map[string]any {\n\treturn map[string]any{\n", t)
	for _, f := range s.Fields {
		p("\t\t%q: %s,\n", f.Name, toAny("s."+exported(f.Name), f.Ty))
	}
	p("\t}\n}\n\n")
}

func emitEnum(b *strings.Builder, name string, e EnumInfo) {
	p := func(format string, x ...any) { fmt.Fprintf(b, format, x...) }
	t := exported(name)
	p("// %s mirrors the Slint enum %q.\n", t, name)
	p("type %s string\n\nconst (\n", t)
	for _, v := range e.Values {
		p("\t%s%s %s = %q\n", t, exported(v), t, v)
	}
	p(")\n\n")
}

// ---- type mapping ----

func goType(t TypeInfo) string {
	switch t.Kind {
	case "int":
		return "int"
	case "float":
		return "float64"
	case "string":
		return "string"
	case "bool":
		return "bool"
	case "color":
		return "slint.Color"
	case "image":
		return "*slint.Image"
	case "enum":
		return exported(t.Name)
	case "struct":
		return exported(t.Name)
	case "array":
		return "[]" + goType(elemOr(t))
	default: // brush (Color|Gradient), other
		return "any"
	}
}

// elemOr returns an array type's element type, or an untyped ("other") element if
// the element type is unknown (renders as `any`).
func elemOr(t TypeInfo) TypeInfo {
	if t.Elem != nil {
		return *t.Elem
	}
	return TypeInfo{Kind: "other"}
}

// fromAny converts an `any` (from Get/callback args) to the typed Go value.
func fromAny(expr string, t TypeInfo) string {
	switch t.Kind {
	case "int":
		return "int(" + expr + ".(float64))"
	case "float":
		return expr + ".(float64)"
	case "string":
		return expr + ".(string)"
	case "bool":
		return expr + ".(bool)"
	case "color":
		return expr + ".(slint.Color)"
	case "image":
		return expr + ".(*slint.Image)"
	case "enum":
		return exported(t.Name) + "(" + expr + ".(slint.Enum).Value)"
	case "struct":
		return unexported(exported(t.Name)) + "FromMap(" + expr + ".(map[string]any))"
	case "array":
		// Models read back as []any; convert each element to the typed element.
		elem := elemOr(t)
		return fmt.Sprintf("func() %s {\n\traw, _ := %s.([]any)\n\tout := make(%s, 0, len(raw))\n\tfor _, e := range raw {\n\t\tout = append(out, %s)\n\t}\n\treturn out\n}()",
			goType(t), expr, goType(t), fromAny("e", elem))
	default:
		return expr
	}
}

// toAny converts a typed Go value to `any` for Set/Invoke/callback return.
func toAny(expr string, t TypeInfo) string {
	switch t.Kind {
	case "enum":
		return fmt.Sprintf("slint.Enum{Type: %q, Value: string(%s)}", t.Name, expr)
	case "struct":
		return expr + ".toMap()"
	case "array":
		// Set/Invoke take []any; cValue turns it into a snapshot model (VecModel).
		elem := elemOr(t)
		return fmt.Sprintf("func() []any {\n\tsrc := %s\n\tout := make([]any, len(src))\n\tfor i, e := range src {\n\t\tout[i] = %s\n\t}\n\treturn out\n}()",
			expr, toAny("e", elem))
	default:
		return expr
	}
}

// ---- identifiers ----

func exported(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '-' || r == '_' || r == ' ' || r == '.' })
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	if b.Len() == 0 {
		return "X"
	}
	return b.String()
}

// unexported lowercases the first letter, so a generated helper (e.g. fromMap) stays
// out of the package's public API.
func unexported(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

// validGoIdent reports whether s is a legal Go identifier (a letter or '_', then
// letters/digits/'_').
func validGoIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r == '_' || unicode.IsLetter(r):
		case i > 0 && unicode.IsDigit(r):
		default:
			return false
		}
	}
	return true
}

// validateNames fails loudly when the generated typed API would not compile because two
// Go identifiers collide — a generated method clashing with a built-in (Run/Show/Close/
// Inner/…) or with another generated member on the same receiver, two package-level
// types with the same name, or a name that isn't a valid Go identifier. format.Source
// only parses the output, so without this an ordinary .slint name like `run`, `show`, or
// `inner` silently yields uncompilable Go and a confusing `go build` failure.
func validateNames(iface *Interface) error {
	comp := exported(iface.Component)

	// methods per receiver: receiver -> method -> origin (origin is used in the message).
	methods := map[string]map[string]string{}
	addMethod := func(recv, method, origin string) error {
		if !validGoIdent(method) {
			return fmt.Errorf("%s maps to method %q, which is not a valid Go identifier — rename it in the .slint", origin, method)
		}
		byName := methods[recv]
		if byName == nil {
			byName = map[string]string{}
			methods[recv] = byName
		}
		if prev, ok := byName[method]; ok {
			return fmt.Errorf("name collision: %s and %s both generate method %q — rename one in the .slint", prev, origin, method)
		}
		byName[method] = origin
		return nil
	}

	// package-level type namespace: name -> origin.
	types := map[string]string{}
	addType := func(name, origin string) error {
		if !validGoIdent(name) {
			return fmt.Errorf("%s maps to type %q, which is not a valid Go identifier — rename it in the .slint", origin, name)
		}
		if prev, ok := types[name]; ok {
			return fmt.Errorf("name collision: %s and %s both generate Go type %q — rename one in the .slint", prev, origin, name)
		}
		types[name] = origin
		return nil
	}

	// registerMembers records the getter/setter/On…/function methods for one receiver.
	registerMembers := func(recv, scope string, props []Prop, callbacks, functions []Callable) error {
		for _, pr := range props {
			m := exported(pr.Name)
			origin := fmt.Sprintf("%sproperty %q", scope, pr.Name)
			if err := addMethod(recv, m, origin); err != nil {
				return err
			}
			if pr.Direction != "out" { // out-only props get no setter (see emitProperties)
				if err := addMethod(recv, "Set"+m, origin); err != nil {
					return err
				}
			}
		}
		for _, c := range callbacks {
			if err := addMethod(recv, "On"+exported(c.Name), fmt.Sprintf("%scallback %q", scope, c.Name)); err != nil {
				return err
			}
		}
		for _, f := range functions {
			if err := addMethod(recv, exported(f.Name), fmt.Sprintf("%sfunction %q", scope, f.Name)); err != nil {
				return err
			}
		}
		return nil
	}

	// component type + its New constructor + built-in methods, then its members.
	if err := addType(comp, fmt.Sprintf("component %q", iface.Component)); err != nil {
		return err
	}
	types["New"+comp] = fmt.Sprintf("the New%s constructor", comp)
	methods[comp] = map[string]string{}
	for _, b := range strings.Fields("Inner Show Hide Close RequestClose Run OnCloseRequested RegisterFontFromPath RegisterFontFromMemory") {
		methods[comp][b] = "a built-in method"
	}
	if err := registerMembers(comp, "", iface.Properties, iface.Callbacks, iface.Functions); err != nil {
		return err
	}

	// exported structs and enums become package-level types (sorted for stable errors).
	for _, name := range sortedKeys(iface.Structs) {
		if err := addType(exported(name), fmt.Sprintf("struct %q", name)); err != nil {
			return err
		}
	}
	for _, name := range sortedKeys(iface.Enums) {
		if err := addType(exported(name), fmt.Sprintf("enum %q", name)); err != nil {
			return err
		}
	}

	// each global: an accessor method on the component + its own type and members.
	for _, g := range iface.Globals {
		if err := addMethod(comp, exported(g.Name), fmt.Sprintf("global %q accessor", g.Name)); err != nil {
			return err
		}
		gType := comp + exported(g.Name)
		if err := addType(gType, fmt.Sprintf("global %q", g.Name)); err != nil {
			return err
		}
		if err := registerMembers(gType, fmt.Sprintf("global %q ", g.Name), g.Properties, g.Callbacks, g.Functions); err != nil {
			return err
		}
	}
	return nil
}

func sortedKeys[V any](m map[string]V) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}
