// Code generated by goslint. DO NOT EDIT.

package ui

import (
	"sync"

	slint "github.com/rileylov/go-slint"
)

var generatedSource = "import { VerticalBox } from \"std-widgets.slint\";\n\nexport component AppWindow inherits Window {\n    in property <image> frame;\n\n    title: \"Go-generated image\";\n    preferred-width: 260px;\n    preferred-height: 260px;\n\n    VerticalBox {\n        Image {\n            source: root.frame;\n            width: 240px;\n            height: 240px;\n        }\n    }\n}\n"

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.Compile(generatedSource, slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

// AppWindow is a typed wrapper around the "AppWindow" component.
type AppWindow struct{ inner *slint.Instance }

// NewAppWindow compiles (once) and instantiates the component.
func NewAppWindow() (*AppWindow, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("AppWindow")
	if err != nil {
		return nil, err
	}
	return &AppWindow{inner: inner}, nil
}

func (c *AppWindow) Inner() *slint.Instance { return c.inner }
func (c *AppWindow) Show() error            { return c.inner.Show() }
func (c *AppWindow) Hide() error            { return c.inner.Hide() }
func (c *AppWindow) Run() error             { return c.inner.Run() }
func (c *AppWindow) Close()                 { c.inner.Close() }
func (c *AppWindow) RequestClose()          { c.inner.RequestClose() }

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *AppWindow) OnCloseRequested(handler func() bool) { c.inner.OnCloseRequested(handler) }

// RegisterFontFromPath/Memory register a custom font for use via `font-family`.
func (c *AppWindow) RegisterFontFromPath(path string) error {
	return c.inner.RegisterFontFromPath(path)
}
func (c *AppWindow) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

func (c *AppWindow) Frame() (*slint.Image, error) {
	v, err := c.inner.Get("frame")
	if err != nil {
		var zero *slint.Image
		return zero, err
	}
	return v.(*slint.Image), nil
}

func (c *AppWindow) SetFrame(value *slint.Image) error {
	return c.inner.Set("frame", value)
}
