// Code generated by goslint. DO NOT EDIT.
//
// This typed API is thread-affine: call New*, the property/callback/function
// methods, and Run on one OS-locked goroutine (the one that runs the event loop).
// Use slint.InvokeFromEventLoop to touch the UI from another goroutine.

package ui

import (
	"embed"
	"os"
	"path/filepath"
	"runtime"
	"sync"

	slint "github.com/rileylov/go-slint"
)

//go:embed app.slint
var slintFS embed.FS

var (
	compileOnce sync.Once
	compiled    *slint.Compilation
	compileErr  error
)

func compile() (*slint.Compilation, error) {
	compileOnce.Do(func() {
		compiled, compileErr = slint.CompileFS(slintFS, "app.slint", slint.WithStyle("fluent"))
	})
	return compiled, compileErr
}

var generatedSourceRel = "app.slint"

func sourcePath() (string, bool) {
	// Primary: next to this generated file (source tree present — go run / goslint dev).
	if _, file, _, ok := runtime.Caller(0); ok {
		p := filepath.Join(filepath.Dir(file), filepath.FromSlash(generatedSourceRel))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	// Fallback: the entry .slint in the working directory (goslint dev runs from
	// the project dir) — robust even if generatedSourceRel doesn't resolve.
	if wd, err := os.Getwd(); err == nil {
		p := filepath.Join(wd, filepath.Base(filepath.FromSlash(generatedSourceRel)))
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

type devRecorder struct {
	replays   []func(*Counter) error
	recording bool
}

// Counter is a typed wrapper around the "Counter" component.
type Counter struct {
	inner *slint.Instance
	rec   *devRecorder // non-nil under GOSLINT_DEV; records setup for live reload
}

// NewCounter compiles (once) and instantiates the component.
func NewCounter() (*Counter, error) {
	app, err := compile()
	if err != nil {
		return nil, err
	}
	inner, err := app.Create("Counter")
	if err != nil {
		return nil, err
	}
	c := &Counter{inner: inner}
	if os.Getenv("GOSLINT_DEV") != "" {
		c.rec = &devRecorder{recording: true}
	}
	return c, nil
}

// Inner returns the underlying *slint.Instance for lower-level access.
func (c *Counter) Inner() *slint.Instance { return c.inner }

// Show makes the window visible without blocking.
func (c *Counter) Show() error { return c.inner.Show() }

// Hide hides the window.
func (c *Counter) Hide() error { return c.inner.Hide() }

// Close releases the component's native resources.
func (c *Counter) Close() { c.inner.Close() }

// RequestClose asks the window to close (fires the OnCloseRequested handler).
func (c *Counter) RequestClose() { c.inner.RequestClose() }

// Run shows the window and runs the event loop. Under `goslint dev` it live-reloads
// the .slint in-process, replaying your setup on each reload.
func (c *Counter) Run() error {
	if c.rec != nil {
		c.rec.recording = false
		if p, ok := sourcePath(); ok {
			c.inner.Close() // discard the not-yet-shown instance; LiveReload makes its own
			return slint.LiveReload(p, "Counter", func(inst *slint.Instance) error {
				c.inner = inst
				for _, replay := range c.rec.replays {
					if err := replay(&Counter{inner: inst}); err != nil {
						return err
					}
				}
				return nil
			}, slint.WithStyle("fluent"))
		}
	}
	return c.inner.Run()
}

// OnCloseRequested runs when the window's close is requested; return true to allow it to close.
func (c *Counter) OnCloseRequested(handler func() bool) {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { t.OnCloseRequested(handler); return nil })
	}
	c.inner.OnCloseRequested(handler)
}

// RegisterFontFromPath registers a custom font file for use via `font-family`.
func (c *Counter) RegisterFontFromPath(path string) error { return c.inner.RegisterFontFromPath(path) }

// RegisterFontFromMemory registers a custom font from memory for use via `font-family`.
func (c *Counter) RegisterFontFromMemory(data []byte) error {
	return c.inner.RegisterFontFromMemory(data)
}

// Value returns the "value" property.
func (c *Counter) Value() (int, error) {
	v, err := c.inner.Get("value")
	if err != nil {
		var zero int
		return zero, err
	}
	n, err := slint.As[float64](v)
	if err != nil {
		return 0, err
	}
	return int(n), nil
}

// SetValue sets the "value" property.
func (c *Counter) SetValue(value int) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.SetValue(value) })
	}
	return c.inner.Set("value", value)
}

// OnIncrement registers a handler for the "increment" callback.
func (c *Counter) OnIncrement(handler func()) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.OnIncrement(handler) })
	}
	return c.inner.OnCallback("increment", func(args []any) any {
		handler()
		return nil
	})
}

// OnReset registers a handler for the "reset" callback.
func (c *Counter) OnReset(handler func()) error {
	if c.rec != nil && c.rec.recording {
		c.rec.replays = append(c.rec.replays, func(t *Counter) error { return t.OnReset(handler) })
	}
	return c.inner.OnCallback("reset", func(args []any) any {
		handler()
		return nil
	})
}
